* Cumulus Overview
https://github.com/paritytech/cumulus/blob/master/docs/overview.md
** Runtime
`Runtime = State Transition Function of a Blockchain`

`Cumulus provides interfaces and extensions to convert a Substrate FRAME runtime into a Parachain runtime`

`Polkadot expects each runtime exposes an interface for validating a Parachain's state transition and also provides interfaces for the Parachain to send and receive messages of other Parachains.`

`When compiling a runtime that uses Cumulus, a WASM binary is generated that contains the full code of the Parachain runtime plus the validate_block functionality. This binary is required to register a Parachain on the relay chain.`

*** validate_block function
explained in pvf_and_pov.org

** Node
`Parachains support light-clients, full nodes, and authority nodes. Authority nodes are called Collators in the Polkadot ecosystem. Cumulus provides the consensus implementation for a Parachain and the block production logic.`

Parachain consensus follows the relaychain to understad which blocks are included and which are finalized.

`Cumulus provides the block production logic that notifies each Collator of the Parachain to build a Parachain block. The notification is triggered on a relay-chain block import by the Collator. This means that every Collator of the Parachain can send a block to the Parachain validators.`

`A Parachain Collator will join the Parachain network and the relay-chain network.`

+ parachain network: `Collators will only gossip blocks to the Parachain network that have a high chance of being included in the relay chain. To prove that a block is probably going to be included, the Collator will send along side the notification the so-called candidate message. This candidate message is issued by a Parachain validator after approving a block. This proof of possible inclusion prevents spamming other collators of the network with useless blocks.` (collators ofc also gossips transactions)
+ relaychain network:
  + `Collator uses it to send the Parachain blocks to the Parachain validators`
  + `the Collator participates as a full-node of the relay chain to be informed of new relay-chain blocks. This information will be used for the consensus and the block production logic.`


** Block Building
explained in pvf_and_pov.org
** Runtime Upgrade
explained in pvf_and_pov.org
